"""Shopify Standard Taxonomy - Seed Data"""
TAXONOMY_DATA = [
    ('1', 'Apparel & Accessories', 'Apparel & Accessories', None, 0, 'clothing fashion wearable garments outfit apparel accessories', '', 'Apparel & Accessories'),
    ('2', 'Arts, Crafts & Sewing', 'Arts, Crafts & Sewing', None, 0, 'crafts art sewing knitting crocheting DIY handmade creative supplies', '', 'Arts, Crafts & Sewing'),
    ('3', 'Automotive', 'Automotive', None, 0, 'car vehicle auto parts accessories maintenance tools garage', '', 'Automotive'),
    ('4', 'Baby', 'Baby', None, 0, 'infant toddler newborn baby products nursery stroller carseat', '', 'Baby'),
    ('5', 'Beauty & Personal Care', 'Beauty & Personal Care', None, 0, 'beauty skincare cosmetics makeup hair care personal care grooming', '', 'Beauty & Personal Care'),
    ('6', 'Books', 'Books', None, 0, 'books literature novels reading textbook fiction nonfiction ebook', '', 'Books'),
    ('7', 'Cameras & Optics', 'Cameras & Optics', None, 0, 'camera photography lens tripod flash memory card accessory optics', '', 'Cameras & Optics'),
    ('8', 'Clothing', 'Clothing', None, 0, 'clothing apparel garments outfit wear shirts pants dress jacket', '', 'Clothing'),
    ('9', 'Collectibles & Fine Art', 'Collectibles & Fine Art', None, 0, 'collectible art vintage antique memorabilia rare limited edition', '', 'Collectibles & Fine Art'),
    ('10', 'Computers & Peripherals', 'Computers & Peripherals', None, 0, 'computer laptop desktop PC keyboard mouse monitor printer hardware', '', 'Computers & Peripherals'),
    ('11', 'Electronics', 'Electronics', None, 0, 'electronics gadgets devices tech digital audio video smart home', '', 'Electronics'),
    ('12', 'Food & Beverage', 'Food & Beverage', None, 0, 'food drink snacks coffee tea chocolate organic natural gourmet', '', 'Food & Beverage'),
    ('13', 'Furniture', 'Furniture', None, 0, 'furniture table chair sofa desk bed couch cabinet shelf bookcase', '', 'Furniture'),
    ('14', 'Health & Wellness', 'Health & Wellness', None, 0, 'health wellness supplements vitamins fitness nutrition organic natural', '', 'Health & Wellness'),
    ('15', 'Home & Garden', 'Home & Garden', None, 0, 'home garden decor kitchen bathroom bedroom living room outdoor', '', 'Home & Garden'),
    ('16', 'Jewelry & Watches', 'Jewelry & Watches', None, 0, 'jewelry watch necklace ring bracelet earring gold silver diamond', '', 'Jewelry & Watches'),
    ('17', 'Luggage & Bags', 'Luggage & Bags', None, 0, 'luggage bag backpack handbag purse suitcase travel carry duffel', '', 'Luggage & Bags'),
    ('18', 'Media', 'Media', None, 0, 'media music movie DVD CD vinyl record digital download streaming', '', 'Media'),
    ('19', 'Office Supplies', 'Office Supplies', None, 0, 'office supplies stationery paper pen pencil desk organizer binder', '', 'Office Supplies'),
    ('20', 'Pet Supplies', 'Pet Supplies', None, 0, 'pet dog cat fish bird animal supplies food toy bed grooming leash', '', 'Pet Supplies'),
    ('21', 'Sporting Goods', 'Sporting Goods', None, 0, 'sports outdoor fitness gym exercise camping hiking cycling running', '', 'Sporting Goods'),
    ('22', 'Toys & Games', 'Toys & Games', None, 0, 'toy game kids children play puzzle board game action figure doll', '', 'Toys & Games'),
    ('23', 'Tools & Home Improvement', 'Tools & Home Improvement', None, 0, 'tools hardware home improvement renovation repair drill saw hammer', '', 'Tools & Home Improvement'),
    ('24', 'Phones & Telecommunications', 'Phones & Telecommunications', None, 0, 'phone mobile smartphone tablet SIM card case charger cable wireless', '', 'Phones & Telecommunications'),
    ('101', 'Clothing', 'Apparel & Accessories > Clothing', '1', 1, 'clothing apparel garments wearable fashion outfit shirts pants dress', 'Apparel', 'Apparel & Accessories'),
    ('102', 'Shoes', 'Apparel & Accessories > Shoes', '1', 1, 'shoes sneakers boots sandals heels loafers slippers footwear', 'Shoes', 'Apparel & Accessories'),
    ('103', 'Accessories', 'Apparel & Accessories > Accessories', '1', 1, 'accessories fashion belt scarf hat gloves sunglasses wallet', 'Accessories', 'Apparel & Accessories'),
    ('104', 'Jewelry', 'Apparel & Accessories > Jewelry', '1', 1, 'jewelry necklace ring bracelet earring pendant gold silver', 'Jewelry', 'Apparel & Accessories'),
    ('105', 'Watches', 'Apparel & Accessories > Watches', '1', 1, 'watch smartwatch analog digital wristwatch timepiece chronograph', 'Watches', 'Apparel & Accessories'),
    ('201', "Men's Clothing", "Clothing > Men's Clothing", '8', 1, 'mens men shirt pants jacket suit blazer sweater hoodie polo', "Men's Clothing", 'Clothing'),
    ('202', "Women's Clothing", "Clothing > Women's Clothing", '8', 1, 'womens women dress blouse skirt top shirt jacket cardigan', "Women's Clothing", 'Clothing'),
    ('203', "Kids' Clothing", "Clothing > Kids' Clothing", '8', 1, 'kids children toddler baby outfit onesie pajamas costume', "Kids' Clothing", 'Clothing'),
    ('204', 'Activewear', 'Clothing > Activewear', '8', 1, 'activewear athletic sportswear workout gym yoga fitness running', 'Activewear', 'Clothing'),
    ('205', 'Outerwear', 'Clothing > Outerwear', '8', 1, 'outerwear jacket coat parka windbreaker rain jacket puffer vest', 'Outerwear', 'Clothing'),
    ('206', 'Swimwear', 'Clothing > Swimwear', '8', 1, 'swimwear swimsuit bathing suit bikini trunks board shorts', 'Swimwear', 'Clothing'),
    ('207', 'Underwear & Lingerie', 'Clothing > Underwear & Lingerie', '8', 1, 'underwear lingerie bra panties boxers briefs sleepwear robe', 'Underwear & Lingerie', 'Clothing'),
    ('208', 'Socks & Hosiery', 'Clothing > Socks & Hosiery', '8', 1, 'socks hosiery tights stockings ankle crew knee compression', 'Socks & Hosiery', 'Clothing'),
    ('209', 'Maternity', 'Clothing > Maternity', '8', 1, 'maternity pregnant expecting baby bump nursing breastfeeding', 'Maternity', 'Clothing'),
    ('210', 'Costumes & Accessories', 'Clothing > Costumes & Accessories', '8', 1, 'costume halloween cosplay dress up themed outfit party', 'Costumes & Accessories', 'Clothing'),
    ('301', 'Skincare', 'Beauty & Personal Care > Skincare', '5', 1, 'skincare moisturizer cleanser serum sunscreen anti-aging face cream', 'Skincare', 'Beauty & Personal Care'),
    ('302', 'Makeup', 'Beauty & Personal Care > Makeup', '5', 1, 'makeup cosmetics foundation lipstick mascara eyeshadow blush concealer', 'Makeup', 'Beauty & Personal Care'),
    ('303', 'Hair Care', 'Beauty & Personal Care > Hair Care', '5', 1, 'hair care shampoo conditioner styling gel serum oil dye color', 'Hair Care', 'Beauty & Personal Care'),
    ('304', 'Fragrance', 'Beauty & Personal Care > Fragrance', '5', 1, 'fragrance perfume cologne eau de toilette mist body spray', 'Fragrance', 'Beauty & Personal Care'),
    ('305', 'Oral Care', 'Beauty & Personal Care > Oral Care', '5', 1, 'oral care toothbrush toothpaste floss mouthwash whitening dental', 'Oral Care', 'Beauty & Personal Care'),
    ('306', 'Bath & Body', 'Beauty & Personal Care > Bath & Body', '5', 1, 'bath body soap body wash lotion scrub oil bubble bath', 'Bath & Body', 'Beauty & Personal Care'),
    ('307', 'Nail Care', 'Beauty & Personal Care > Nail Care', '5', 1, 'nail polish remover manicure pedicure nail art nail care', 'Nail Care', 'Beauty & Personal Care'),
    ('308', 'Shaving & Hair Removal', 'Beauty & Personal Care > Shaving & Hair Removal', '5', 1, 'shave razor blade cream aftershave trimmer epilator wax', 'Shaving & Hair Removal', 'Beauty & Personal Care'),
    ('401', 'Audio', 'Electronics > Audio', '11', 1, 'audio speaker headphones earbuds soundbar amplifier receiver microphone', 'Audio', 'Electronics'),
    ('402', 'Video', 'Electronics > Video', '11', 1, 'video TV monitor display projector screen streaming player Blu-ray', 'Video', 'Electronics'),
    ('403', 'Smart Home', 'Electronics > Smart Home', '11', 1, 'smart home hub thermostat light switch camera doorbell lock speaker', 'Smart Home', 'Electronics'),
    ('404', 'Wearable Technology', 'Electronics > Wearable Technology', '11', 1, 'wearable smartwatch fitness tracker band health monitor GPS', 'Wearable Technology', 'Electronics'),
    ('405', 'Car Electronics', 'Electronics > Car Electronics', '11', 1, 'car electronics GPS navigation dashcam stereo receiver amplifier', 'Car Electronics', 'Electronics'),
    ('406', 'Portable Audio & Video', 'Electronics > Portable Audio & Video', '11', 1, 'portable audio speaker earbuds headphones MP3 player recorder', 'Portable Audio & Video', 'Electronics'),
    ('501', 'Kitchen', 'Home & Garden > Kitchen', '15', 1, 'kitchen cookware bakeware appliance utensil gadget knife cutting board', 'Kitchen', 'Home & Garden'),
    ('502', 'Bedding', 'Home & Garden > Bedding', '15', 1, 'bedding sheets pillow blanket comforter duvet mattress pad quilt', 'Bedding', 'Home & Garden'),
    ('503', 'Bath', 'Home & Garden > Bath', '15', 1, 'bath towel shower curtain bath mat faucet sink toilet accessories', 'Bath', 'Home & Garden'),
    ('504', 'Home Decor', 'Home & Garden > Home Decor', '15', 1, 'home decor wall art candle vase picture frame clock mirror rug', 'Home Decor', 'Home & Garden'),
    ('505', 'Storage & Organization', 'Home & Garden > Storage & Organization', '15', 1, 'storage organization bin shelf drawer closet hanger organizer basket', 'Storage & Organization', 'Home & Garden'),
    ('506', 'Outdoor Living', 'Home & Garden > Outdoor Living', '15', 1, 'outdoor patio garden furniture grill plant pot planter hose', 'Outdoor Living', 'Home & Garden'),
    ('507', 'Lighting', 'Home & Garden > Lighting', '15', 1, 'lighting lamp bulb LED ceiling wall floor table night light', 'Lighting', 'Home & Garden'),
    ('508', 'Cleaning Supplies', 'Home & Garden > Cleaning Supplies', '15', 1, 'cleaning supplies vacuum mop broom duster detergent sanitizer wipe', 'Cleaning Supplies', 'Home & Garden'),
    ('601', 'Exercise & Fitness', 'Sporting Goods > Exercise & Fitness', '21', 1, 'exercise fitness gym workout yoga mat dumbbell resistance band weight', 'Exercise & Fitness', 'Sporting Goods'),
    ('602', 'Cycling', 'Sporting Goods > Cycling', '21', 1, 'cycling bike bicycle helmet pump tire tube pedal chain gear', 'Cycling', 'Sporting Goods'),
    ('603', 'Outdoor Recreation', 'Sporting Goods > Outdoor Recreation', '21', 1, 'outdoor camping hiking fishing hunting tent sleeping bag backpack', 'Outdoor Recreation', 'Sporting Goods'),
    ('604', 'Team Sports', 'Sporting Goods > Team Sports', '21', 1, 'team sports football basketball soccer baseball softball volleyball', 'Team Sports', 'Sporting Goods'),
    ('605', 'Water Sports', 'Sporting Goods > Water Sports', '21', 1, 'water sports surfing kayaking paddleboard snorkeling swim goggles', 'Water Sports', 'Sporting Goods'),
    ('606', 'Golf', 'Sporting Goods > Golf', '21', 1, 'golf club ball tee bag cart glove shoe apparel rangefinder', 'Golf', 'Sporting Goods'),
    ('607', 'Winter Sports', 'Sporting Goods > Winter Sports', '21', 1, 'winter ski snowboard boots bindings goggles helmet jacket gloves', 'Winter Sports', 'Sporting Goods'),
    ('701', 'Action Figures & Collectibles', 'Toys & Games > Action Figures & Collectibles', '22', 1, 'action figure collectible model statue superhero comic anime POP', 'Action Figures & Collectibles', 'Toys & Games'),
    ('702', 'Building Toys', 'Toys & Games > Building Toys', '22', 1, 'building blocks LEGO STEM construction engineering magnetic tiles', 'Building Toys', 'Toys & Games'),
    ('703', 'Dolls & Accessories', 'Toys & Games > Dolls & Accessories', '22', 1, 'doll accessories stuffed animal plush toy baby doll fashion doll', 'Dolls & Accessories', 'Toys & Games'),
    ('704', 'Games', 'Toys & Games > Games', '22', 1, 'board game card game puzzle strategy trivia party family classic', 'Games', 'Toys & Games'),
    ('705', 'Outdoor Play', 'Toys & Games > Outdoor Play', '22', 1, 'outdoor play swing slide sandbox trampoline water gun sprinkler', 'Outdoor Play', 'Toys & Games'),
    ('706', 'Educational Toys', 'Toys & Games > Educational Toys', '22', 1, 'educational STEM learning science math coding robot kit experiment', 'Educational Toys', 'Toys & Games'),
    ('707', 'Puzzles', 'Toys & Games > Puzzles', '22', 1, 'puzzle jigsaw brain teaser 3D wooden floor kid adult challenging', 'Puzzles', 'Toys & Games'),
    ('801', 'Nursery', 'Baby > Nursery', '4', 1, 'nursery crib mattress bedding monitor changing table decor lamp', 'Nursery', 'Baby'),
    ('802', 'Strollers & Car Seats', 'Baby > Strollers & Car Seats', '4', 1, 'stroller carseat carrier travel system jogging umbrella lightweight', 'Strollers & Car Seats', 'Baby'),
    ('803', 'Feeding', 'Baby > Feeding', '4', 1, 'feeding bottle breast pump highchair bib burp cloth formula food', 'Feeding', 'Baby'),
    ('804', 'Baby Clothing', 'Baby > Baby Clothing', '4', 1, 'baby clothing onesie bodysuit pajamas booties hat mittens bib', 'Baby Clothing', 'Baby'),
    ('805', 'Diapering', 'Baby > Diapering', '4', 1, 'diaper changing pad wipes cream rash holder bag dispenser', 'Diapering', 'Baby'),
    ('806', 'Safety & Health', 'Baby > Safety & Health', '4', 1, 'baby safety gate monitor thermometer medicine cabinet first aid', 'Safety & Health', 'Baby'),
    ('901', 'Dog Supplies', 'Pet Supplies > Dog Supplies', '20', 1, 'dog supplies food treat toy bed crate leash collar harness grooming', 'Dog Supplies', 'Pet Supplies'),
    ('902', 'Cat Supplies', 'Pet Supplies > Cat Supplies', '20', 1, 'cat supplies food litter toy scratcher tree bed collar carrier', 'Cat Supplies', 'Pet Supplies'),
    ('903', 'Bird Supplies', 'Pet Supplies > Bird Supplies', '20', 1, 'bird supplies cage food seed perch toy feeder waterer', 'Bird Supplies', 'Pet Supplies'),
    ('904', 'Fish Supplies', 'Pet Supplies > Fish Supplies', '20', 1, 'fish aquarium tank filter food pump heater light decoration', 'Fish Supplies', 'Pet Supplies'),
    ('905', 'Small Animal Supplies', 'Pet Supplies > Small Animal Supplies', '20', 1, 'small animal hamster guinea pig rabbit ferret cage bedding food', 'Small Animal Supplies', 'Pet Supplies'),
    ('1001', 'Snacks & Confectionery', 'Food & Beverage > Snacks & Confectionery', '12', 1, 'snacks candy chocolate chips cookies crackers popcorn granola bar', 'Snacks & Confectionery', 'Food & Beverage'),
    ('1002', 'Beverages', 'Food & Beverage > Beverages', '12', 1, 'beverages coffee tea juice water energy drink soda kombucha', 'Beverages', 'Food & Beverage'),
    ('1003', 'Pantry Staples', 'Food & Beverage > Pantry Staples', '12', 1, 'pantry staples flour sugar rice pasta sauce oil vinegar spice', 'Pantry Staples', 'Food & Beverage'),
    ('1004', 'Organic & Natural', 'Food & Beverage > Organic & Natural', '12', 1, 'organic natural non-GMO vegan gluten-free whole food plant-based', 'Organic & Natural', 'Food & Beverage'),
    ('1005', 'Specialty Diet', 'Food & Beverage > Specialty Diet', '12', 1, 'specialty diet keto paleo vegan gluten-free low-sugar sugar-free', 'Specialty Diet', 'Food & Beverage'),
    ('1101', 'Fine Jewelry', 'Jewelry & Watches > Fine Jewelry', '16', 1, 'fine jewelry gold silver diamond platinum gemstone precious stone', 'Fine Jewelry', 'Jewelry & Watches'),
    ('1102', 'Fashion Jewelry', 'Jewelry & Watches > Fashion Jewelry', '16', 1, 'fashion jewelry costume statement trendy boho minimalist chunky', 'Fashion Jewelry', 'Jewelry & Watches'),
    ('1103', 'Watches', 'Jewelry & Watches > Watches', '16', 1, 'watch analog digital smartwatch automatic chronograph dive field', 'Watches', 'Jewelry & Watches'),
    ('1104', 'Wedding & Engagement', 'Jewelry & Watches > Wedding & Engagement', '16', 1, 'wedding engagement ring bridal set band promise anniversary', 'Wedding & Engagement', 'Jewelry & Watches'),
    ('1201', 'Living Room Furniture', 'Furniture > Living Room Furniture', '13', 1, 'living room sofa couch chair coffee table end table bookshelf TV stand', 'Living Room Furniture', 'Furniture'),
    ('1202', 'Bedroom Furniture', 'Furniture > Bedroom Furniture', '13', 1, 'bedroom bed frame headboard nightstand dresser mirror wardrobe', 'Bedroom Furniture', 'Furniture'),
    ('1203', 'Office Furniture', 'Furniture > Office Furniture', '13', 1, 'office desk chair bookshelf filing cabinet standing desk ergonomic', 'Office Furniture', 'Furniture'),
    ('1204', 'Outdoor Furniture', 'Furniture > Outdoor Furniture', '13', 1, 'outdoor patio furniture chair table umbrella bench swing hammock', 'Outdoor Furniture', 'Furniture'),
    ('1205', 'Dining & Entertaining', 'Furniture > Dining & Entertaining', '13', 1, 'dining table chair set bench hutch buffet sideboard bar cart', 'Dining & Entertaining', 'Furniture'),
    ('1301', 'Supplements & Vitamins', 'Health & Wellness > Supplements & Vitamins', '14', 1, 'supplements vitamins mineral protein powder omega collagen probiotic', 'Supplements & Vitamins', 'Health & Wellness'),
    ('1302', 'Fitness Equipment', 'Health & Wellness > Fitness Equipment', '14', 1, 'fitness equipment dumbbell kettlebell resistance band yoga mat treadmill', 'Fitness Equipment', 'Health & Wellness'),
    ('1303', 'Wellness', 'Health & Wellness > Wellness', '14', 1, 'wellness meditation aromatherapy essential oil diffuser relaxation stress', 'Wellness', 'Health & Wellness'),
    ('1304', 'Natural Remedies', 'Health & Wellness > Natural Remedies', '14', 1, 'natural remedies herbal supplement homeopathic tea tincture essential oil', 'Natural Remedies', 'Health & Wellness'),
    ('1305', 'Personal Protective Equipment', 'Health & Wellness > Personal Protective Equipment', '14', 1, 'PPE mask face shield glove sanitizer disinfectant protective', 'Personal Protective Equipment', 'Health & Wellness'),
    ('1401', 'Power Tools', 'Tools & Home Improvement > Power Tools', '23', 1, 'power tool drill saw sander grinder router jigsaw circular saw', 'Power Tools', 'Tools & Home Improvement'),
    ('1402', 'Hand Tools', 'Tools & Home Improvement > Hand Tools', '23', 1, 'hand tool hammer wrench screwdriver pliers tape measure level socket', 'Hand Tools', 'Tools & Home Improvement'),
    ('1403', 'Hardware', 'Tools & Home Improvement > Hardware', '23', 1, 'hardware screw nail bolt nut washer hinge latch knob handle', 'Hardware', 'Tools & Home Improvement'),
    ('1404', 'Plumbing', 'Tools & Home Improvement > Plumbing', '23', 1, 'plumbing faucet pipe valve fitting sink toilet shower head', 'Plumbing', 'Tools & Home Improvement'),
    ('1405', 'Electrical', 'Tools & Home Improvement > Electrical', '23', 1, 'electrical outlet switch wire breaker panel dimmer smart plug', 'Electrical', 'Tools & Home Improvement'),
    ('1406', 'Painting & Wallpaper', 'Tools & Home Improvement > Painting & Wallpaper', '23', 1, 'paint brush roller sprayer primer sealer wallpaper paste stripper', 'Painting & Wallpaper', 'Tools & Home Improvement'),
    ('1501', 'Craft Supplies', 'Arts, Crafts & Sewing > Craft Supplies', '2', 1, 'craft supplies paper fabric glue paint marker brush stamp sticker', 'Craft Supplies', 'Arts, Crafts & Sewing'),
    ('1502', 'Sewing', 'Arts, Crafts & Sewing > Sewing', '2', 1, 'sewing machine fabric thread needle pattern scissors measuring tape', 'Sewing', 'Arts, Crafts & Sewing'),
    ('1503', 'Knitting & Crocheting', 'Arts, Crafts & Sewing > Knitting & Crocheting', '2', 1, 'knitting crochet yarn needle hook pattern gauge stitch wip', 'Knitting & Crocheting', 'Arts, Crafts & Sewing'),
    ('1504', 'Art Supplies', 'Arts, Crafts & Sewing > Art Supplies', '2', 1, 'art supplies canvas paint acrylic watercolor brush easel sketch pad', 'Art Supplies', 'Arts, Crafts & Sewing'),
    ('1601', 'Cell Phones', 'Phones & Telecommunications > Cell Phones', '24', 1, 'cell phone smartphone mobile iPhone Android Samsung Galaxy OnePlus', 'Cell Phones', 'Phones & Telecommunications'),
    ('1602', 'Phone Cases & Accessories', 'Phones & Telecommunications > Phone Cases & Accessories', '24', 1, 'phone case cover screen protector charger cable mount stand holder', 'Phone Cases & Accessories', 'Phones & Telecommunications'),
    ('1603', 'Tablets', 'Phones & Telecommunications > Tablets', '24', 1, 'tablet iPad Android Samsung Galaxy Amazon Kindle e-reader drawing', 'Tablets', 'Phones & Telecommunications'),
    ('1604', 'SIM Cards & Plans', 'Phones & Telecommunications > SIM Cards & Plans', '24', 1, 'SIM card plan prepaid data roaming international call text', 'SIM Cards & Plans', 'Phones & Telecommunications'),
    ('1701', 'Laptops', 'Computers & Peripherals > Laptops', '10', 1, 'laptop notebook MacBook Dell HP Lenovo Chromebook gaming ultrabook', 'Laptops', 'Computers & Peripherals'),
    ('1702', 'Desktops', 'Computers & Peripherals > Desktops', '10', 1, 'desktop PC tower iMac Mac Mini workstation gaming Raspberry Pi', 'Desktops', 'Computers & Peripherals'),
    ('1703', 'Monitors', 'Computers & Peripherals > Monitors', '10', 1, 'monitor display screen LED LCD OLED curved ultrawide 4K gaming', 'Monitors', 'Computers & Peripherals'),
    ('1704', 'Printers & Scanners', 'Computers & Peripherals > Printers & Scanners', '10', 1, 'printer scanner ink toner paper 3D laserjet inkjet receipt', 'Printers & Scanners', 'Computers & Peripherals'),
    ('1705', 'Networking', 'Computers & Peripherals > Networking', '10', 1, 'networking router WiFi mesh switch Ethernet cable modem access point', 'Networking', 'Computers & Peripherals'),
    ('1706', 'Storage', 'Computers & Peripherals > Storage', '10', 1, 'storage SSD HDD hard drive flash USB thumb external cloud backup', 'Storage', 'Computers & Peripherals'),
    ('1801', 'Luggage', 'Luggage & Bags > Luggage', '17', 1, 'luggage suitcase carry-on checked rolling hard shell soft expandable', 'Luggage', 'Luggage & Bags'),
    ('1802', 'Backpacks', 'Luggage & Bags > Backpacks', '17', 1, 'backpack bookbag laptop travel hiking school military tactical', 'Backpacks', 'Luggage & Bags'),
    ('1803', 'Handbags & Purses', 'Luggage & Bags > Handbags & Purses', '17', 1, 'handbag purse tote clutch crossbody shoulder bag satchel wallet', 'Handbags & Purses', 'Luggage & Bags'),
    ('1804', 'Travel Accessories', 'Luggage & Bags > Travel Accessories', '17', 1, 'travel accessories packing cube luggage tag toiletry bag passport holder', 'Travel Accessories', 'Luggage & Bags'),
    ('1901', 'Car Care', 'Automotive > Car Care', '3', 1, 'car care wax polish clay bar cleaner tire shine glass cleaner', 'Car Care', 'Automotive'),
    ('1902', 'Interior Accessories', 'Automotive > Interior Accessories', '3', 1, 'car interior seat cover floor mat organizer phone mount air freshener', 'Interior Accessories', 'Automotive'),
    ('1903', 'Exterior Accessories', 'Automotive > Exterior Accessories', '3', 1, 'car exterior cover rack bike hitch winch light bar bull bar', 'Exterior Accessories', 'Automotive'),
    ('1904', 'Performance Parts', 'Automotive > Performance Parts', '3', 1, 'performance parts exhaust intake turbo suspension brake chip tune', 'Performance Parts', 'Automotive'),
    ('2001', 'Shirts', "Clothing > Men's Clothing > Shirts", '201', 2, 'shirt t-shirt polo dress shirt button-down flannel Hawaiian denim', 'Shirts', 'Clothing'),
    ('2002', 'Pants', "Clothing > Men's Clothing > Pants", '201', 2, 'pants jeans chinos shorts cargo sweatpants joggers dress pants', 'Pants', 'Clothing'),
    ('2003', 'Suits & Blazers', "Clothing > Men's Clothing > Suits & Blazers", '201', 2, 'suit blazer tuxedo vest tie bow tie pocket square formal', 'Suits & Blazers', 'Clothing'),
    ('2004', 'Sweaters & Hoodies', "Clothing > Men's Clothing > Sweaters & Hoodies", '201', 2, 'sweater hoodie pullover crewneck zip-up cardigan fleece knit', 'Sweaters & Hoodies', 'Clothing'),
    ('2005', 'Jackets & Coats', "Clothing > Men's Clothing > Jackets & Coats", '201', 2, 'jacket coat blazer vest windbreaker rain parka down bomber', 'Jackets & Coats', 'Clothing'),
    ('2101', 'Dresses', "Clothing > Women's Clothing > Dresses", '202', 2, 'dress maxi mini cocktail casual formal evening wrap A-line fit flare', 'Dresses', 'Clothing'),
    ('2102', 'Tops & Blouses', "Clothing > Women's Clothing > Tops & Blouses", '202', 2, 'top blouse shirt tunic tank cami bodysuit crop graphic floral', 'Tops & Blouses', 'Clothing'),
    ('2103', 'Skirts', "Clothing > Women's Clothing > Skirts", '202', 2, 'skirt midi maxi mini pencil pleated A-line denim leather tennis', 'Skirts', 'Clothing'),
    ('2104', 'Pants & Leggings', "Clothing > Women's Clothing > Pants & Leggings", '202', 2, 'pants leggings jeans wide-leg palazzo joggers denim culottes', 'Pants & Leggings', 'Clothing'),
    ('2105', 'Jackets & Coats', "Clothing > Women's Clothing > Jackets & Coats", '202', 2, 'jacket coat blazer cardigan trench rain puffer down leather denim', 'Jackets & Coats', 'Clothing'),
    ('3001', 'Cleansers', 'Beauty & Personal Care > Skincare > Cleansers', '301', 2, 'cleanser face wash makeup remover micellar water foam gel oil balm', 'Cleansers', 'Beauty & Personal Care'),
    ('3002', 'Moisturizers', 'Beauty & Personal Care > Skincare > Moisturizers', '301', 2, 'moisturizer cream lotion serum hydrating plumping anti-aging night day', 'Moisturizers', 'Beauty & Personal Care'),
    ('3003', 'Sunscreen', 'Beauty & Personal Care > Skincare > Sunscreen', '301', 2, 'sunscreen SPF sun protection mineral chemical zinc oxide face body', 'Sunscreen', 'Beauty & Personal Care'),
    ('3004', 'Acne Treatment', 'Beauty & Personal Care > Skincare > Acne Treatment', '301', 2, 'acne treatment spot treatment cleanser toner salicylic benzoyl peroxide', 'Acne Treatment', 'Beauty & Personal Care'),
    ('3005', 'Anti-Aging', 'Beauty & Personal Care > Skincare > Anti-Aging', '301', 2, 'anti-aging retinol serum collagen peptide vitamin C wrinkle firm', 'Anti-Aging', 'Beauty & Personal Care'),
    ('5001', 'Cookware', 'Home & Garden > Kitchen > Cookware', '501', 2, 'cookware pan skillet pot dutch oven wok grill griddle pressure steamer', 'Cookware', 'Home & Garden'),
    ('5002', 'Bakeware', 'Home & Garden > Kitchen > Bakeware', '501', 2, 'bakeware baking sheet pan muffin cake cookie loaf silicone mold', 'Bakeware', 'Home & Garden'),
    ('5003', 'Kitchen Appliances', 'Home & Garden > Kitchen > Kitchen Appliances', '501', 2, 'kitchen appliance blender mixer toaster oven microwave air fryer coffee', 'Kitchen Appliances', 'Home & Garden'),
    ('5004', 'Kitchen Utensils', 'Home & Garden > Kitchen > Kitchen Utensils', '501', 2, 'kitchen utensil spatula spoon tongs ladle whisk peel grater timer', 'Kitchen Utensils', 'Home & Garden'),
    ('5005', 'Knives & Cutlery', 'Home & Garden > Kitchen > Knives & Cutlery', '501', 2, 'knife chef paring utility steak knife set sharpener cutting board', 'Knives & Cutlery', 'Home & Garden'),
    ('6001', 'Yoga', 'Sporting Goods > Exercise & Fitness > Yoga', '601', 2, 'yoga mat block strap towel mat bag bolster cushion meditation', 'Yoga', 'Sporting Goods'),
    ('6002', 'Strength Training', 'Sporting Goods > Exercise & Fitness > Strength Training', '601', 2, 'strength training dumbbell kettlebell barbell weight bench rack cable', 'Strength Training', 'Sporting Goods'),
    ('6003', 'Cardio', 'Sporting Goods > Exercise & Fitness > Cardio', '601', 2, 'cardio treadmill elliptical bike rowing machine jump rope stepper', 'Cardio', 'Sporting Goods'),
    ('6004', 'Recovery', 'Sporting Goods > Exercise & Fitness > Recovery', '601', 2, 'recovery foam roller massage gun compression bandage brace wrap', 'Recovery', 'Sporting Goods'),
    ('9001', 'Dog Food', 'Pet Supplies > Dog Supplies > Dog Food', '901', 2, 'dog food dry wet grain-free organic puppy senior treats kibble', 'Dog Food', 'Pet Supplies'),
    ('9002', 'Dog Toys', 'Pet Supplies > Dog Supplies > Dog Toys', '901', 2, 'dog toy chew bone rope puzzle fetch ball plush squeaky interactive', 'Dog Toys', 'Pet Supplies'),
    ('9003', 'Dog Beds & Furniture', 'Pet Supplies > Dog Supplies > Dog Beds & Furniture', '901', 2, 'dog bed crate kennel mat cushion orthopedic bolster elevated travel', 'Dog Beds & Furniture', 'Pet Supplies'),
    ('9004', 'Dog Grooming', 'Pet Supplies > Dog Supplies > Dog Grooming', '901', 2, 'dog grooming shampoo brush clipper nail trimmer deshedding ear cleaner', 'Dog Grooming', 'Pet Supplies'),
    ('2201', 'T-Shirts', "Clothing > Men's Clothing > Shirts > T-Shirts", '2001', 3, 't-shirt tee graphic plain crew neck V-neck pocket oversized slim', 'T-Shirts', 'Clothing'),
    ('2202', 'Dress Shirts', "Clothing > Men's Clothing > Shirts > Dress Shirts", '2001', 3, 'dress shirt button-down formal business wrinkle-free slim fit spread', 'Dress Shirts', 'Clothing'),
    ('2301', 'Casual Dresses', "Clothing > Women's Clothing > Dresses > Casual Dresses", '2101', 3, 'casual dress everyday summer floral print cotton maxi midi mini', 'Casual Dresses', 'Clothing'),
    ('2302', 'Formal Dresses', "Clothing > Women's Clothing > Dresses > Formal Dresses", '2101', 3, 'formal dress evening gown prom bridesmaid cocktail party wedding guest', 'Formal Dresses', 'Clothing'),
    ('3101', 'Face Serums', 'Beauty & Personal Care > Skincare > Moisturizers > Face Serums', '3002', 3, 'face serum vitamin C hyaluronic acid niacinamide retinol antioxidant', 'Face Serums', 'Beauty & Personal Care'),
    ('5101', 'Frying Pans', 'Home & Garden > Kitchen > Cookware > Frying Pans', '5001', 3, 'frying pan skillet non-stick cast iron stainless steel ceramic induction', 'Frying Pans', 'Home & Garden'),
    ('5102', 'Saucepans', 'Home & Garden > Kitchen > Cookware > Saucepans', '5001', 3, 'saucepan pot sauce stock pot stockpot tea kettle milk frother', 'Saucepans', 'Home & Garden'),
]