# Generated by Django 6.1 on 2026-08-25 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_category_path', models.CharField(blank=True, default='', max_length=512)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_classified', 'Auto Classified'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('review_reason', models.TextField(blank=True, default='')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('classification_method', models.CharField(default='hybrid', max_length=50)),
                ('lexical_score', models.FloatField(default=0.0)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('image_score', models.FloatField(default=0.0)),
                ('hint_score', models.FloatField(default=0.0)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('processed_products', models.PositiveIntegerField(default=0)),
                ('successful_classifications', models.PositiveIntegerField(default=0)),
                ('failed_classifications', models.PositiveIntegerField(default=0)),
                ('reviews_needed', models.PositiveIntegerField(default=0)),
                ('use_llm', models.BooleanField(default=False)),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classification Batch',
                'verbose_name_plural': 'Classification Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=64, unique=True)),
                ('product_name', models.CharField(max_length=512)),
                ('product_description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('source_category', models.CharField(blank=True, default='', max_length=255)),
                ('source_subcategory', models.CharField(blank=True, default='', max_length=255)),
                ('materials', models.CharField(blank=True, default='', max_length=255)),
                ('product_weight', models.FloatField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=64)),
                ('product_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('classification_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlternativeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_path', models.CharField(max_length=512)),
                ('confidence', models.FloatField(default=0.0)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_categories', to='classification.classification')),
            ],
            options={
                'verbose_name': 'Alternative Category',
                'verbose_name_plural': 'Alternative Categories',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_value', models.CharField(max_length=512)),
                ('confidence', models.FloatField(default=0.9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='classification.classification')),
            ],
            options={
                'verbose_name': 'Classification Attribute',
                'verbose_name_plural': 'Classification Attributes',
                'ordering': ['attribute_name'],
            },
        ),
        migrations.AddField(
            model_name='classification',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='classification.product'),
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_path', models.CharField(max_length=512)),
                ('level', models.SmallIntegerField(default=0)),
                ('keywords', models.TextField(blank=True, default='')),
                ('product_type_hint', models.CharField(blank=True, default='', max_length=255)),
                ('top_level_category', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='classification.taxonomycategory')),
            ],
            options={
                'verbose_name': 'Taxonomy Category',
                'verbose_name_plural': 'Taxonomy Categories',
                'ordering': ['full_path'],
            },
        ),
        migrations.AddField(
            model_name='classification',
            name='taxonomy_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='classification.taxonomycategory')),
    ]
